/**
 * Tracks which socket currently "owns" each physical device.
 *
 * Key  : stable deviceId generated by the client and sent in socket auth.
 * Value: current socket.id that holds the session for that device.
 *
 * Only one socket per deviceId is allowed in production.
 * The mapping is cleaned up on every socket disconnect.
 */

const store = new Map<string, string>(); // deviceId → socketId

export const deviceSessionRepository = {
  /**
   * Attempt to register a new session for a device.
   *
   * @returns The existing socketId that already owns the device,
   *          or `null` when registration succeeds (no conflict).
   */
  tryRegister(deviceId: string, socketId: string): string | null {
    const existing = store.get(deviceId);
    if (existing && existing !== socketId) return existing; // conflict
    store.set(deviceId, socketId);
    return null;
  },

  /**
   * Force-register a device → socket mapping, evicting any previous owner.
   * Called when a client exercises "Use This Tab / take over".
   */
  forceRegister(deviceId: string, socketId: string): void {
    store.set(deviceId, socketId);
  },

  /** Remove the mapping for the given socket (called on disconnect). */
  unregisterBySocket(socketId: string): void {
    for (const [deviceId, sid] of store) {
      if (sid === socketId) {
        store.delete(deviceId);
        break;
      }
    }
  },

  /** Resolve which socket currently owns a device, if any. */
  getByDeviceId(deviceId: string): string | undefined {
    return store.get(deviceId);
  },
};
